# Logistic Regression Implementation

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [7]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
import pandas as pd 
import numpy as np 

In [9]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
df['target'] = dataset.target

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [13]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
## Binary Classification 
df_copy = df[df['target'] != 2]

In [22]:
df_copy['target'].unique()

array([0, 1])

In [24]:
# Independent and dependent feature.
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1]

In [32]:
# Test train split data 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=20, random_state=42)

In [40]:
## Logstic Regression 
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

In [48]:
classifier.predict_proba(X_test) # show the probability of getting that value in output.

array([[0.00118455, 0.99881545],
       [0.01579803, 0.98420197],
       [0.00304709, 0.99695291],
       [0.96959941, 0.03040059],
       [0.94269372, 0.05730628],
       [0.97161144, 0.02838856],
       [0.99356322, 0.00643678],
       [0.0316902 , 0.9683098 ],
       [0.97460702, 0.02539298],
       [0.9789308 , 0.0210692 ],
       [0.95512884, 0.04487116],
       [0.96072669, 0.03927331],
       [0.00430743, 0.99569257],
       [0.98586374, 0.01413626],
       [0.00927792, 0.99072208],
       [0.98146423, 0.01853577],
       [0.00207948, 0.99792052],
       [0.00125531, 0.99874469],
       [0.97461564, 0.02538436],
       [0.96116169, 0.03883831]])

In [41]:
classifier

LogisticRegression()

In [42]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [43]:
# Prediction 
y_pred = classifier.predict(X_test)

In [44]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

# confusion_metrix, accuracy score, classification

In [45]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [47]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# Hyperparameter Tuning

In [49]:
## Gridsearchcv 
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [50]:
parameters={
    'penalty':('l1','l2','elasticnet',None),
    "C":[1,20,30]
}

In [51]:
clf = GridSearchCV(classifier,param_grid=parameters,cv=5)

In [52]:
# Splitting of Train data to validation data 
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [53]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [54]:
classifier = LogisticRegression(C=1,penalty='l2')

In [55]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [56]:
## Predection 
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [57]:
## Here accuray is approx same but it will increse in case of large dataset.abs

In [58]:
# Randomized Searchcv 
from sklearn.model_selection import RandomizedSearchCV

In [59]:
random_clf = RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)

In [60]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [61]:
random_clf.best_params_

{'penalty': 'l2', 'C': 20}